"""CLI driver + worker pool for synthetic dataset generation.

    python -m src.generator.generate --config <yaml> [--n-workers N] [--smoke]

Each image is generated by ``core.generate_one_image`` and is fully reproducible
from ``(config + base_seed + git commit)``. The pool reuses the
``src.calibration.study`` BLAS-pinning pattern: 'spawn' workers, a ``_init_worker``
that pins OMP/MKL/OpenBLAS to 1 BEFORE numpy is imported.

THIS MODULE INTENTIONALLY IMPORTS NOTHING HEAVY AT TOP (no numpy, no simulator).
The numpy-bearing build/render logic is imported lazily, after thread pinning,
inside ``_build_spec`` / ``_worker_run`` — identical discipline to study.py, so
``n_workers ≈ cores`` without BLAS oversubscription. Keep it that way.
"""

import argparse
import hashlib
import json
import multiprocessing as mp
import os
import time
from pathlib import Path

import yaml

from src.calibration.study import _init_worker      # BLAS-pinning (no numpy at top)
from src.provenance import write_provenance


# --------------------------------------------------------------------------- #
# Spec building (main process; lazy heavy imports after pinning)              #
# --------------------------------------------------------------------------- #
def _flatten_sampling_cfg(config):
    """Collect the flat sampling knobs ``sample_image_params``/``core`` consume."""
    sampling = dict(config.get('sampling', {}) or {})
    cfg = {
        'protein_brightness_range': sampling.get('protein_brightness_range'),
        'noise_split_range': sampling.get('noise_split_range', [0.2, 5.0]),
        'optical_bg_lipid_range': sampling.get('optical_bg_lipid_range', [0.0, 7.0]),
        'eccentricity_range': sampling.get('eccentricity_range', [0.9, 1.1]),
        'fixed_spot_density': sampling.get('fixed_spot_density'),
        'alpha_range': config.get('alpha_range', [0.5, 2.0]),
        'mixed_global_prob': config.get('mixed_global_prob', 0.5),
    }
    if cfg['protein_brightness_range'] is None:
        raise ValueError("config.sampling.protein_brightness_range is required")
    return cfg


def _build_spec(config, config_path):
    """Build the picklable, numpy-free spec passed to every worker.

    Heavy imports happen HERE (after the caller has pinned BLAS threads). All
    values in the returned spec are plain Python (lists/dicts/floats/str) so
    unpickling it in a worker does NOT import numpy before the initializer runs.
    """
    from src.generator.calibration_io import (
        build_param_ranges, build_regimes, load_calibration)
    from src.generator.size_distribution import curvature_emphasis_pmf, dls_pmf

    cal_paths = list(config['calibrations'])
    calibrations = [load_calibration(p) for p in cal_paths]
    ranges = build_param_ranges(
        calibrations, widen_frac=float(config.get('widen_frac', 0.3)))
    regimes = build_regimes(calibrations)

    size_mode = config.get('size_mode', 'emphasis')
    if size_mode == 'emphasis':
        s = config.get('size', {}) or {}
        diameters, probs = curvature_emphasis_pmf(
            float(s.get('d_min', 40.0)), float(s.get('d_max', 300.0)),
            int(s.get('n_bins', 256)), float(s.get('size_emphasis', 1.0)))
    elif size_mode == 'dls':
        d = config.get('dls', {}) or {}
        if not d.get('path'):
            raise ValueError("size_mode 'dls' requires config.dls.path")
        diameters, probs = dls_pmf(
            d['path'], d.get('weighting', 'number'),
            int(d.get('max_diameter_nm', 500)))
    else:
        raise ValueError(f"unknown size_mode '{size_mode}' (use emphasis|dls)")

    config_hash = hashlib.sha256(
        json.dumps(config, sort_keys=True, default=str).encode()).hexdigest()[:16]
    name = config['name']
    output_dir = config.get('output_dir') or str(Path('datasets') / name)

    return {
        'name': name,
        'output_dir': output_dir,
        'n_images': int(config['n_images']),
        'image_size': int(config.get('image_size', 256)),
        'base_seed': int(config.get('base_seed', 0)),
        'alpha_mode': config.get('alpha_mode', 'per_spot_random'),
        'size_mode': size_mode,
        'cfg': _flatten_sampling_cfg(config),
        'ranges': ranges,
        'regimes': regimes,
        'diameters': [float(x) for x in diameters],   # plain lists -> no numpy at unpickle
        'probs': [float(x) for x in probs],
        'config_hash': config_hash,
        'calibrations': [str(p) for p in cal_paths],
    }


# --------------------------------------------------------------------------- #
# Worker (process-global spec set by the initializer)                         #
# --------------------------------------------------------------------------- #
_SPEC = None


def _worker_init(spec):
    """Pool initializer: pin BLAS threads (study.py), then stash the spec.

    Runs in each worker BEFORE numpy is imported. ``spec`` is pure Python, so
    unpickling it here does not import numpy ahead of the pinning.
    """
    _init_worker()
    global _SPEC
    _SPEC = spec


def _worker_run(index):
    """Generate + serialize one image (heavy imports happen here, post-pinning)."""
    from src.generator.core import generate_one_image, serialize_image
    image, label = generate_one_image(index, _SPEC)
    return serialize_image(_SPEC['output_dir'], index, image, label)


# --------------------------------------------------------------------------- #
# Orchestration                                                               #
# --------------------------------------------------------------------------- #
def run_generation(config, config_path, n_workers=None, smoke=False):
    """Generate a full dataset; write images, labels, manifest, provenance.

    Returns the list of per-image records. If ``smoke`` is True, ``n_images`` is
    reduced to ``config.smoke.n_images`` (default 8) and smoke plots are written.
    """
    # Pin the main process too (mirrors study.py's serial path) BEFORE numpy.
    _init_worker()

    if smoke:
        smoke_cfg = config.get('smoke', {}) or {}
        config = dict(config)
        config['n_images'] = int(smoke_cfg.get('n_images', 8))

    spec = _build_spec(config, config_path)
    out_dir = Path(spec['output_dir'])
    (out_dir / 'images').mkdir(parents=True, exist_ok=True)
    (out_dir / 'labels').mkdir(parents=True, exist_ok=True)

    n_images = int(spec['n_images'])
    indices = list(range(n_images))
    if n_workers is None:
        n_workers = os.cpu_count() or 1
    n_workers = max(1, min(int(n_workers), max(1, n_images)))

    print('=' * 60)
    print(f"[generate] name={spec['name']}  n_images={n_images}  "
          f"n_workers={n_workers}  alpha_mode={spec['alpha_mode']}  "
          f"size_mode={spec['size_mode']}")
    print(f"[generate] output_dir={out_dir}")
    print('=' * 60)

    t0 = time.time()
    records = []
    if n_workers == 1:
        _worker_init(spec)
        for i in indices:
            records.append(_worker_run(i))
    else:
        ctx = mp.get_context('spawn')
        with ctx.Pool(n_workers, initializer=_worker_init, initargs=(spec,)) as pool:
            for rec in pool.imap_unordered(_worker_run, indices, chunksize=4):
                records.append(rec)
    records.sort(key=lambda r: r['index'])
    duration = time.time() - t0

    _write_manifest(spec, records, duration)
    try:
        write_provenance(
            out_dir, config_path,
            name=spec['name'], n_images=len(records),
            base_seed=spec['base_seed'], alpha_mode=spec['alpha_mode'],
            size_mode=spec['size_mode'], config_hash=spec['config_hash'],
            calibrations=spec['calibrations'])
    except Exception as e:
        print(f"  warning: provenance write failed: {e}")

    n_spots = sum(r['n_spots'] for r in records)
    print(f"[generate] DONE in {duration:.1f}s  images={len(records)}  "
          f"spots={n_spots}")

    if smoke:
        from src.generator.smoke import make_smoke_plots
        written = make_smoke_plots(out_dir, records, config)
        for p in written:
            print(f"[generate] smoke plot: {p}")

    return records


def _write_manifest(spec, records, duration):
    """Write ``dataset_manifest.json`` summarizing the run."""
    out = Path(spec['output_dir'])
    manifest = {
        'name': spec['name'],
        'n_images': len(records),
        'n_spots_total': sum(r['n_spots'] for r in records),
        'image_shape': [2, spec['image_size'], spec['image_size']],
        'channels': ['protein', 'lipid'],
        'alpha_mode': spec['alpha_mode'],
        'size_mode': spec['size_mode'],
        'base_seed': spec['base_seed'],
        'config_hash': spec['config_hash'],
        'calibrations': spec['calibrations'],
        'regimes': [r['name'] for r in spec['regimes']],
        'param_ranges': spec['ranges'],
        'duration_sec': round(duration, 2),
    }
    (out / 'dataset_manifest.json').write_text(json.dumps(manifest, indent=2))
    print(f"[generate] wrote dataset_manifest.json to {out}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate a synthetic two-channel liposome dataset.')
    parser.add_argument('--config', required=True,
                        help='Path to a generator YAML config.')
    parser.add_argument('--n-workers', type=int, default=None,
                        help='Worker processes (default: os.cpu_count()).')
    parser.add_argument('--smoke', action='store_true',
                        help='Tiny batch + comparison/overlay smoke plots.')
    args = parser.parse_args()

    with open(args.config) as f:
        config = yaml.safe_load(f)
    run_generation(config, args.config, n_workers=args.n_workers, smoke=args.smoke)


if __name__ == '__main__':
    main()
